const launch = document.querySelector('.launch button')
const header = document.querySelector('header')
const footer = document.querySelector('footer')
const background = document.querySelector('.background')
const train = document.querySelector('.dynamic-elements')
const carriers = document.querySelectorAll('div[class^="catenary-carrier-"]')
const controlLeft = document.querySelector('.move-left')
const controlRight = document.querySelector('.move-right')

launch.addEventListener('click', () => {
  header.classList.add('disable')
  footer.classList.add('disable')
  launch.classList.add('disable')
  background.classList.add('enable')
  carriers.forEach(carrier => {
    carrier.classList.add('actives')
    carrier.classList.add('animation')
  })
  train.classList.add('animation')
  controlLeft.classList.add('hide')
  controlRight.classList.add('hide')
})